In [7]:
import numpy as np

#np.random.normal(loc, #среднее - по умолчанию 0 scale, #стандартное отклонение - по умолчанию 1, size #размер выборки)
#или

#rng = np.random.default_ng()
#rng.normal(loc, scale, size)

#например
np.random.normal(loc=100, scale=20, size=10)
#среднее = 30
#стандартное отклонение = 3
#размер выборки равен 1000


array([135.94172652, 111.01571645,  86.26791024,  68.79393778,
        92.94239201, 115.00041905,  98.37487557,  82.06527636,
        61.51403808,  84.2964803 ])

In [9]:
import scipy.stats as st

#наш метод
st.norm.ppf(q=[0.025, 0.975], loc=100, scale=10)

array([ 80.40036015, 119.59963985])

In [11]:
st.norm.ppf(q=[0.005, 0.995], loc=0, scale=1)

array([-2.5758293,  2.5758293])

In [12]:
import seaborn as sns

tips = sns.load_dataset("tips")
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [15]:
bill_mean = tips['total_bill'].mean()
bill_mean

19.78594262295082

In [16]:
bill_std = tips['total_bill'].std()
bill_std

8.902411954856856

In [17]:
tips['z-values_bill'] = (tips['total_bill'] - bill_mean) / bill_std

In [18]:
tips

total_bill   tip     sex smoker   day    time  size  z-values_bill
0         16.99  1.01  Female     No   Sun  Dinner     2      -0.314066
1         10.34  1.66    Male     No   Sun  Dinner     3      -1.061054
2         21.01  3.50    Male     No   Sun  Dinner     3       0.137497
3         23.68  3.31    Male     No   Sun  Dinner     2       0.437416
4         24.59  3.61  Female     No   Sun  Dinner     4       0.539635
..          ...   ...     ...    ...   ...     ...   ...            ...
239       29.03  5.92    Male     No   Sat  Dinner     3       1.038377
240       27.18  2.00  Female    Yes   Sat  Dinner     2       0.830568
241       22.67  2.00    Male    Yes   Sat  Dinner     2       0.323964
242       17.82  1.75    Male     No   Sat  Dinner     2      -0.220833
243       18.78  3.00  Female     No  Thur  Dinner     2      -0.112997

[244 rows x 8 columns]

In [19]:
tips["z-values_bill_scipy"] = st.zscore(tips["total_bill"], ddof=1)

tips

In [22]:
tips['z-values_bill'].std()

1.0

In [26]:
from scipy.stats import norm

# Для стандартного нормального распределения (μ=0, σ=1)
print(norm.cdf(0)) # Выведет 0.5 (вероятность быть меньше 0)

# Для произвольного распределения
mean = 100
std_dev = 15
print(norm.cdf(115, loc=mean, scale=std_dev)) # Вероятность быть меньше 115

0.5
0.8413447460685429


Вы провели расчеты и выяснили, что среди студентов курса по статистике распределение роста является нормальным со средним значением, равным 173, и стандартным отклонением, равным 11.

Приблизительно какой процент студентов имеет рост на интервале от 181 до 192? Ответ округлите до целого.

In [34]:
import scipy.stats as st
less_than_181 = st.norm.cdf(loc=173, scale=11, x=181)
less_than_192 = st.norm.cdf(loc=173, scale=11, x=192)

less_than_192 - less_than_181

0.19147010345862991